name: update

on:
  push: # Trigger on push to master
    branches:
      - main

jobs:
  update-game-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Update game list
        run: npm start
      - uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: latest
          artifacts: "games.json"
          token: ${{ secrets.GITHUB_TOKEN }}
      
